### ISSUE TITLE
no `mstcpip` in `shared`

### ISSUE THREAD

**Issue by Jasperav** [krojew/cdrs-tokio#10]
When I try to run any test, I get this error message:

```
error[E0432]: unresolved import `winapi::shared::mstcpip`
  --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\mio-0.7.10\src\sys\windows\tcp.rs:13:5
   |
13 | use winapi::shared::mstcpip;
   |     ^^^^^^^^^^^^^^^^^^^^^^^ no `mstcpip` in `shared`
```

I am running Windows 10. I had no problem running https://github.com/AlexPikalov/cdrs. Do you know why this error occurs?

**Comment by krojew** [comment]
Seems like you ran into a problem with mio: https://github.com/tokio-rs/mio/commit/a7e61db9e3c2b929ef1a33532bfcc22045d163ce

It's fixed in 0.7.11 and works in 0.7.9.

**Comment by Jasperav** [comment]
Thanks @krojew, cargo update worked
